// <auto-generated />
using HW4_Ynfante.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HW4_Ynfante.Migrations
{
    [DbContext(typeof(SeasonScheduleContext))]
    [Migration("20210718160855_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HW4_Ynfante.Models.SeasonSchedule", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opponent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeekId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            WeekId = 1,
                            Date = "Sun, Sep 12",
                            Opponent = "Indianapolis",
                            TeamLogo = "Indianapolis.png",
                            Time = "12:00 PM",
                            Tv = "FOX",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 2,
                            Date = "Sun, Sep 19",
                            Opponent = "Tennessee",
                            TeamLogo = "Tennessee.png",
                            Time = "3:25 PM",
                            Tv = "CBS",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 3,
                            Date = "Sun, Sep 26",
                            Opponent = "Minnesota",
                            TeamLogo = "Minnesota.png",
                            Time = "3:25 PM",
                            Tv = "FOX",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 4,
                            Date = "Sun, Oct 3",
                            Opponent = "San Francisco",
                            TeamLogo = "San Francisco.png",
                            Time = "3:05 PM",
                            Tv = "FOX",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 5,
                            Date = "Thu, Oct 7",
                            Opponent = "Los Angeles",
                            TeamLogo = "Los Angeles.png",
                            Time = "7:20 PM",
                            Tv = "FOX, NFL",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 6,
                            Date = "Sun, Oct 17",
                            Opponent = "Pittsburgh",
                            TeamLogo = "Pittsburgh.png",
                            Time = "7:20 PM",
                            Tv = "NBC",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 7,
                            Date = "Mon, Oct 25",
                            Opponent = "New Orleans",
                            TeamLogo = "New Orleans.png",
                            Time = "7:15 PM",
                            Tv = "ESPN",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 8,
                            Date = "Sun, Oct 31",
                            Opponent = "Jacksonville",
                            TeamLogo = "Jacksonville.png",
                            Time = "3:05 PM",
                            Tv = "CBS",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 9,
                            Date = "BYE WEEK",
                            Opponent = "",
                            TeamLogo = "blank.png",
                            Time = "",
                            Tv = "",
                            Vs = ""
                        },
                        new
                        {
                            WeekId = 10,
                            Date = "Sun, Nov 14",
                            Opponent = "Green Bay",
                            TeamLogo = "Green Bay.png",
                            Time = "3:25 PM",
                            Tv = "CBS",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 11,
                            Date = "Sun, Nov 21",
                            Opponent = "Arizona",
                            TeamLogo = "Arizona.png",
                            Time = "3:25 PM",
                            Tv = "FOX",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 12,
                            Date = "Mon, Nov 29",
                            Opponent = "Washington",
                            TeamLogo = "Washington.png",
                            Time = "7:15 PM",
                            Tv = "ESPN",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 13,
                            Date = "Sun, Dec 5",
                            Opponent = "San Francisco",
                            TeamLogo = "San Francisco.png",
                            Time = "7:20 PM",
                            Tv = "NBC",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 14,
                            Date = "Sun, Dec 12",
                            Opponent = "Houston",
                            TeamLogo = "Houston.png",
                            Time = "12:00 PM",
                            Tv = "FOX",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 15,
                            Date = "Sun, Dec 19",
                            Opponent = "Los Angeles",
                            TeamLogo = "Los Angeles.png",
                            Time = "3:25 PM",
                            Tv = "FOX",
                            Vs = "@"
                        },
                        new
                        {
                            WeekId = 16,
                            Date = "Sun, Dec 26",
                            Opponent = "Chicago",
                            TeamLogo = "Chicago.png",
                            Time = "3:05 PM",
                            Tv = "FOX",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 17,
                            Date = "Sun, Jan 2",
                            Opponent = "Detroit",
                            TeamLogo = "Detroit.png",
                            Time = "3:25 PM",
                            Tv = "FOX",
                            Vs = "vs"
                        },
                        new
                        {
                            WeekId = 18,
                            Date = "Sun, Jan 9",
                            Opponent = "Arizona",
                            TeamLogo = "Arizona.png",
                            Time = "3:25 PM",
                            Tv = "FOX",
                            Vs = "@"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
